### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [neurospeech/web-atoms-core#103]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/neurospeech/web-atoms-core/blob/master/package.json#L29

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

Same for `path`: https://github.com/neurospeech/web-atoms-core/blob/master/package.json#L32

**Comment by ackava** [comment]
@DanielRuf thanks, I have removed it.
